#!/bin/sh
# Git remote helper for git-secure-export, see gitremote-helpers(7).

if [ ! -e "$GIT_DIR/git-secure-key" ]; then
	cat 1>&2 <<-EOF
		*
		* git-remote-secure cannot clone repositories as the
		* symmetric key, needed for decrypting the repository,
		* must be provided first.
		*
		* If you have access to the symmetric key:
		*
		*  1. Manually initialize the repository using git-init(1).
		*  2. Copy the symmetric key to the .git/ directory.
		*  3. Add the secure:// remote manually and pull.
		*
EOF
	exit 1
fi

# From gitremote-helpers(7):
#  The second argument specifies a URL; it is usually of the form
#  <transport>://<address>, but any arbitrary string is possible.
URL="$2"

get_host() {
	echo "$URL" | sed 's|^..*://\(..*\):.*|\1|'
}

get_path() {
	echo "$URL" | sed 's|^..*://..*:\(.*\)|\1|'
}

# git-secure-import only encrypts data as specified in the INPUT
# FORMAT section of git-fast-import(1). Similarly, git-secure-import
# only decrypt data matching this format. All other data is simply
# copied from standard input to standard output.
git-secure-export | \
	ssh "$(get_host)" "git-secure-receive $(get_path)" | \
	git-secure-import
